# 1.1 PyTorch useful function 

### Syllabus
1. torch.tensor
2. torch math operation
3. torch tensor grad
4. torch documentation

## 1. torch.tensor

In [1]:
import torch
#version of pytorch
print(torch.__version__)

1.10.0+cu111


In [2]:
a = torch.tensor(1) #you can specify the type of tensor by using this parameter dtype inside the declaration
print(a)
print(a.dtype)
print(a.shape)

tensor(1)
torch.int64
torch.Size([])


In [3]:
b = torch.tensor(7.5)
print(b)
print(b.dtype)
print(b.shape)

tensor(7.5000)
torch.float32
torch.Size([])


In [4]:
#you can specify the type of tensor by using this parameter dtype inside the declaration
c = torch.tensor(16, dtype=torch.float16)
print(c)
print(c.dtype)

tensor(16., dtype=torch.float16)
torch.float16


In [6]:
#you can pass list and tuple to tensor
d = torch.tensor([[1,2,3],[4,5,6]])
f = torch.tensor((7,3))

In [7]:
print(d, d.dtype)
print(f, f.dtype)

tensor([[1, 2, 3],
        [4, 5, 6]]) torch.int64
tensor([7, 3]) torch.int64


In [9]:
#tensor and numpy
import numpy as np

x = np.array([[1,2,3,4],[5,6,7,8]])
print(x, x.dtype)
x = torch.tensor(x)
print(x, x.dtype)
x = x.numpy()
print(x, x.dtype)

[[1 2 3 4]
 [5 6 7 8]] int64
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]]) torch.int64
[[1 2 3 4]
 [5 6 7 8]] int64


## 2. Torch Math Operation

In [10]:
a = torch.tensor([1,2,3,4])
b = torch.tensor([2,3,4,5])

In [12]:
#add
print(f'add: torch {torch.add(a,b)} regular {a+b}')
#subtract
print(f'subtract: torch {torch.subtract(b,a)} regular {b-a}')
#multiply
print(f'multiply: torch {torch.mul(b,a)} regular {b*a}')
#divide
print(f'divide: torch {torch.divide(b,a)} regular {b/a}')

add: torch tensor([3, 5, 7, 9]) regular tensor([3, 5, 7, 9])
subtract: torch tensor([1, 1, 1, 1]) regular tensor([1, 1, 1, 1])
multiply: torch tensor([ 2,  6, 12, 20]) regular tensor([ 2,  6, 12, 20])
divide: torch tensor([2.0000, 1.5000, 1.3333, 1.2500]) regular tensor([2.0000, 1.5000, 1.3333, 1.2500])


In [18]:
#sum
print(f"sum {torch.sum(a)}")
#average
print(f"average {torch.mean(a.float())}") #need to convert from int to float so the average can be done
#standar deviation
print(f"standar deviation {torch.std(a.float())}")

sum 10
average 2.5
standar deviation 1.29099440574646


In [20]:
#matrix multiplication
a = torch.tensor([[2,2],[3,3]])
b = torch.tensor([[1,2],[3,4]])

print(f"matmul torch {torch.matmul(a,b)} \n reguler {a@b}")

matmul torch tensor([[ 8, 12],
        [12, 18]]) 
 reguler tensor([[ 8, 12],
        [12, 18]])


## 3. torch tensor grad

we are gonna make function
y = 3x^2 + 3x^3 and we are gonna doing some derivatives -> dy/dx -> y' = 6x +9x^2

for x = 3

In [30]:
x = torch.tensor(3 , dtype=torch.float32, requires_grad=True)
y = 3*x**2 +3*x**3
print(y)
y.backward()
print("dy/dx: ",x.grad)

tensor(108., grad_fn=<AddBackward0>)
dx/dy:  tensor(99.)


lets make it even more complicated
lets do y = 3x^5 - 10w^4 + 8z and than print dy/dx, dy/dw, dy/dz

for x = 3, w = 1, z = 2

In [31]:
w = torch.tensor(1 , dtype=torch.float32, requires_grad=True)
z = torch.tensor(2 , dtype=torch.float32, requires_grad=True)

y = 3*x**5 - 10*w**4 + 8*z
print(y)
y.backward()
print("dy/dx: ", x.grad)
print("dy/dw: ", w.grad)
print("dy/dz: ", z.grad)

tensor(735., grad_fn=<AddBackward0>)
dy/dx:  tensor(1314.)
dy/dw:  tensor(-40.)
dy/dz:  tensor(8.)


## 4. Torch.documentations
you can check the whole documentation of pytorch at https://pytorch.org/docs/stable/index.html