<a href="https://colab.research.google.com/github/rubythalib33/Sekolah-AI-Indonesia/blob/main/Course%201.%20Pytorch%2BLightning%20Coureses%20Level%201/1_2_ANN_training_with_dummy_datasets_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1.2 ANN training with dummy datasets

Syllabus:
1. create a linear function for the dummy datasets
2. create dummy datasets
3. create model
4. create training scheme
5. create inference function

## 1. create a linear function for the dummy datasets

for this tutorial we are gonna make this function for the datasets,
f(x1,x2,x3,x4) = x1*w1+x2*w2+x3*w3+x4*w4
w1 = 1
w2 = 2
w3 = 3
w4 = 4

In [1]:
def function(x1, x2, x3, x4):
  w1,w2,w3,w4 = 1,2,3,4
  return  x1*w1+x2*w2+x3*w3+x4*w4

In [2]:
#example
x1,x2,x3,x4 = 1,2,3,4
function(x1,x2,x3,x4) #1+4+9+16=30

30

## 2. create dummy datasets


In [3]:
import numpy as np

In [4]:
def create_dummy_datasets(n=1000):
  x = np.random.randint(0, 2000, size=(n,4))

  y = []
  for i in x:
    y_temp = function(*i) #i[0], i[1], ..., i[n-1] n: panjang arraynya
    y.append(y_temp)
  
  y = np.asarray(y)

  return x,y

In [5]:
N_SAMPLE = 1000
data = create_dummy_datasets(N_SAMPLE)

In [6]:
print(data[0]) #for the x data
print(data[1]) #for the y data

[[1042  489  312  524]
 [ 698  930  956 1897]
 [1135 1418 1224  247]
 ...
 [1274  464  852  514]
 [1802  487  680  628]
 [1991  847  575  601]]
[ 5052 13014  8631  4350  9763  9412  9945  7878  9264 11796 11308 10063
 14541  8747  7679  8473  6904  8625 10110  5285  6753  9260  6563  7119
  6228 16696  9014 11774  6735  8197 10769  7303 16538 11124 12427 10108
 11846  9771  8700  6438  6432  8399  9184  6659  7058 10896 10232 11546
  9657  8398  8448 17337 12466  6739  7390  4741 11225 15410 14088  8676
 10839  8214 10179  8285  8959 10010  4893  6424  6079  7282 11248  7779
  7067 14540  9534 11983  6121  8299 13283  7494  5072  7887  8429  9676
  3535 12493 12399 13374  8639 11472 16162  9455  8243  4992 12026 12338
  9363 11949  8268 13436 10955  8418  7102 13685  6328  5222 11508 11933
 12913 12051  7076 12429  6855 11317  4715  6039 12093 16983 14851 10074
  9835 11570  5289  8644 15639  8072  9530  8743 11502 12927  7356 18398
 10488  9106  3800 12349  6537 17966  8656  9024  549

In [7]:
#lets convert it to torch.tensor dtype torch.float32 so it can run smoothly on neural nets
import torch

In [8]:
X = torch.tensor(data[0], dtype = torch.float32)
y = torch.tensor(data[1], dtype = torch.float32)

In [9]:
print(X)
print(y)

tensor([[1042.,  489.,  312.,  524.],
        [ 698.,  930.,  956., 1897.],
        [1135., 1418., 1224.,  247.],
        ...,
        [1274.,  464.,  852.,  514.],
        [1802.,  487.,  680.,  628.],
        [1991.,  847.,  575.,  601.]])
tensor([ 5052., 13014.,  8631.,  4350.,  9763.,  9412.,  9945.,  7878.,  9264.,
        11796., 11308., 10063., 14541.,  8747.,  7679.,  8473.,  6904.,  8625.,
        10110.,  5285.,  6753.,  9260.,  6563.,  7119.,  6228., 16696.,  9014.,
        11774.,  6735.,  8197., 10769.,  7303., 16538., 11124., 12427., 10108.,
        11846.,  9771.,  8700.,  6438.,  6432.,  8399.,  9184.,  6659.,  7058.,
        10896., 10232., 11546.,  9657.,  8398.,  8448., 17337., 12466.,  6739.,
         7390.,  4741., 11225., 15410., 14088.,  8676., 10839.,  8214., 10179.,
         8285.,  8959., 10010.,  4893.,  6424.,  6079.,  7282., 11248.,  7779.,
         7067., 14540.,  9534., 11983.,  6121.,  8299., 13283.,  7494.,  5072.,
         7887.,  8429.,  9676.,  3535.

## 3.lets build a model

In [11]:
from torch import nn

In [12]:
class RegressionModel(nn.Module):
  def __init__(self, input_node=4, output_node=1):
    super().__init__()
    self.input_node = input_node
    self.output_node = output_node

    self.fc = nn.Linear(self.input_node, self.output_node, bias=False) #we want to make the bias false so it can relate with the function but in most cases you need the bias to be true
  
  def forward(self,x):
    return self.fc(x)

## 4. Let's Create training scheme
before that let's understand about concept of optimization and loss function

In [13]:
sample_model = RegressionModel()
optim = torch.optim.SGD(sample_model.parameters(), lr=0.001) #Stochastic Gradient Descent
loss_fn = nn.MSELoss() #Mean Squared error loss

In [18]:
sample_X = X
sample_y = y

BATCH_SIZE = 10
sample_X = torch.reshape(sample_X, (N_SAMPLE//BATCH_SIZE, BATCH_SIZE, 4)) #let's make batch 10 | (N_SAMPLE,4) -> (N_SAMPLE//BATCH_SIZE, BATCH_SIZE, 4) -> (100, 10, 4)
sample_y = torch.reshape(sample_y, (N_SAMPLE//BATCH_SIZE, BATCH_SIZE, 1)) #let's make batch 10 | (N_SAMPLE,1) -> (N_SAMPLE//BATCH_SIZE, BATCH_SIZE, 1) -> (100, 10, 1)

sample_X = sample_X/2000
sample_y = sample_y/2000

In [19]:
print(sample_X.shape)
print(sample_y.shape)
print(sample_model)

torch.Size([100, 10, 4])
torch.Size([100, 10, 1])
RegressionModel(
  (fc): Linear(in_features=4, out_features=1, bias=False)
)


In [44]:
#this is what we call one epoch training
for i in range(1000):
  print("EPOCH ", i)
  for i, (inputs, target) in enumerate(zip(sample_X, sample_y)):
    output = sample_model(inputs)
    loss = loss_fn(output,target)
    if i % 10 == 0:
      print("   step ",i)
      print(loss.item())
    # Backpropagation
    optim.zero_grad()
    loss.backward()
    optim.step()

Output streaming akan dipotong hingga 5000 baris terakhir.
   step  90
3.732639974884933e-09
EPOCH  762
   step  0
4.6235073547507e-09
   step  10
6.173320521440928e-09
   step  20
7.392872980460652e-09
   step  30
2.5630995104108933e-09
   step  40
5.437209349423711e-09
   step  50
9.91686066598163e-10
   step  60
5.896430455010204e-09
   step  70
7.550819525192765e-09
   step  80
5.8118132528761635e-09
   step  90
3.732639974884933e-09
EPOCH  763
   step  0
4.6235073547507e-09
   step  10
6.173320521440928e-09
   step  20
7.392872980460652e-09
   step  30
2.5630995104108933e-09
   step  40
5.437209349423711e-09
   step  50
9.91686066598163e-10
   step  60
5.896430455010204e-09
   step  70
7.550819525192765e-09
   step  80
5.8118132528761635e-09
   step  90
3.732639974884933e-09
EPOCH  764
   step  0
4.6235073547507e-09
   step  10
6.173320521440928e-09
   step  20
7.392872980460652e-09
   step  30
2.5630995104108933e-09
   step  40
5.437209349423711e-09
   step  50
9.91686066598163e-

In [45]:
#lets see the total loss
loss_total = []
for inputs, target in zip(sample_X, sample_y):
  output = sample_model(inputs)
  loss = loss_fn(output,target)
  loss_total.append(loss.item())

loss_average = np.mean(loss_total)

In [47]:
print(loss_average)

4.772375521433503e-09


In [48]:
#lets we see the parameters, that's the weight that we trained
for param in sample_model.parameters():
  print(param.data)

tensor([[1.0001, 2.0000, 3.0001, 3.9998]])


## 5. create inference function

In [49]:
def inference(x1,x2,x3,x4):
  inputs = torch.tensor([[x1,x2,x3,x4]], dtype=torch.float32)
  inputs = inputs/2000
  output = sample_model(inputs)
  output*=2000

  return output[0].detach().numpy()

In [50]:
x1,x2,x3,x4 = 3,4,5,6
inference(x1,x2,x3,x4), function(x1,x2,x3,x4)

(array([49.99949], dtype=float32), 50)