<a href="https://colab.research.google.com/github/rubythalib33/Sekolah-AI-Indonesia/blob/main/1_2_ANN_training_with_dummy_datasets_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1.2 ANN training with dummy datasets

Syllabus:
1. create a linear function for the dummy datasets
2. create dummy datasets
3. create model
4. create training scheme
5. create inference function

## 1. create a linear function for the dummy datasets

for this tutorial we are gonna make this function for the datasets,
f(x1,x2,x3,x4) = x1*w1+x2*w2+x3*w3+x4*w4
w1 = 1
w2 = 2
w3 = 3
w4 = 4

In [1]:
def function(x1, x2, x3, x4):
  w1,w2,w3,w4 = 1,2,3,4
  return  x1*w1+x2*w2+x3*w3+x4*w4

In [2]:
#example
x1,x2,x3,x4 = 1,2,3,4
function(x1,x2,x3,x4) #1+4+9+16=30

30

## 2. create dummy datasets


In [3]:
import numpy as np

In [4]:
def create_dummy_datasets(n=1000):
  x = np.random.randint(0, 2000, size=(n,4))

  y = []
  for i in x:
    y_temp = function(*i)
    y.append(y_temp)
  
  y = np.asarray(y)

  return x,y

In [5]:
N_SAMPLE = 1000
data = create_dummy_datasets(N_SAMPLE)

In [6]:
print(data[0]) #for the x data
print(data[1]) #for the y data

[[ 649 1793  718 1142]
 [ 584 1118  172  369]
 [ 294 1799  753  768]
 ...
 [1452 1692 1888 1232]
 [ 218  996  687  337]
 [1284  238  795  125]]
[10957  4812  9223  3342  7267 12423  3064 12719  2948 10068 12489  7525
 10357  3164 12704  6618  5905  7229 10380 12079 12356  8662  7644  5355
  9878 10441  6055 14110  5387  6892 15147  9717 16136 16993  8686  9039
 11559 12619  8484 14507 11397  7415 11504  9625 14831 15811 11714  7412
  2923 11064 10912 14662  8290 15270 15561 13827 15620  9189  7091  9214
 10585  9648 13160  7507  6234 11582 15680 13419  8714  9963 11917  7999
  9430  6987 11457  9120 15856  7571 11238 13706  4266 12992  9686  3726
 10052 11005  6315 12305 14994 10004  9697  4641 10591 10684 13900 11600
  9790  8168  5663 13529  7442 10702 13957  9709  7818 12676  9305  7997
 12691  7240  9355 10058  8400 13761 10762 10175  9404 12001  7421  8848
  8681 11014 10024  4394  7416  9235  7189 12270  7809 12189 10915  6597
  9106 17446 10535  9583  9272 12127 10901  8297 1040

In [7]:
#lets convert it to torch.tensor dtype torch.float32 so it can run smoothly on neural nets
import torch

In [8]:
X = torch.tensor(data[0], dtype = torch.float32)
y = torch.tensor(data[1], dtype = torch.float32)

In [9]:
print(X)
print(y)

tensor([[ 649., 1793.,  718., 1142.],
        [ 584., 1118.,  172.,  369.],
        [ 294., 1799.,  753.,  768.],
        ...,
        [1452., 1692., 1888., 1232.],
        [ 218.,  996.,  687.,  337.],
        [1284.,  238.,  795.,  125.]])
tensor([10957.,  4812.,  9223.,  3342.,  7267., 12423.,  3064., 12719.,  2948.,
        10068., 12489.,  7525., 10357.,  3164., 12704.,  6618.,  5905.,  7229.,
        10380., 12079., 12356.,  8662.,  7644.,  5355.,  9878., 10441.,  6055.,
        14110.,  5387.,  6892., 15147.,  9717., 16136., 16993.,  8686.,  9039.,
        11559., 12619.,  8484., 14507., 11397.,  7415., 11504.,  9625., 14831.,
        15811., 11714.,  7412.,  2923., 11064., 10912., 14662.,  8290., 15270.,
        15561., 13827., 15620.,  9189.,  7091.,  9214., 10585.,  9648., 13160.,
         7507.,  6234., 11582., 15680., 13419.,  8714.,  9963., 11917.,  7999.,
         9430.,  6987., 11457.,  9120., 15856.,  7571., 11238., 13706.,  4266.,
        12992.,  9686.,  3726., 10052.

## 3.lets build a model

In [10]:
from torch import nn

In [11]:
class RegressionModel(nn.Module):
  def __init__(self, input_node=4, output_node=1):
    super().__init__()
    self.input_node = input_node
    self.output_node = output_node

    self.fc = nn.Linear(self.input_node, self.output_node, bias=False) #we want to make the bias false so it can relate with the function but in most cases you need the bias to be true
  
  def forward(self,x):
    return self.fc(x)

## 4. Let's Create training scheme
before that let's understand about concept of optimization and loss function

In [12]:
sample_model = RegressionModel()
optim = torch.optim.SGD(sample_model.parameters(), lr=0.001) #Stochastic Gradient Descent
loss_fn = nn.MSELoss() #Mean Squared error loss

In [13]:
sample_X = X
sample_y = y

BATCH_SIZE = 10
sample_X = torch.reshape(sample_X, (N_SAMPLE//BATCH_SIZE, BATCH_SIZE, 4)) #let's make batch 10
sample_y = torch.reshape(sample_y, (N_SAMPLE//BATCH_SIZE, BATCH_SIZE, 1)) #let's make batch 10

sample_X = sample_X/2000
sample_y = sample_y/2000

In [14]:
print(sample_X)
print(sample_y)
print(sample_model)

tensor([[[0.3245, 0.8965, 0.3590, 0.5710],
         [0.2920, 0.5590, 0.0860, 0.1845],
         [0.1470, 0.8995, 0.3765, 0.3840],
         ...,
         [0.3750, 0.6200, 0.9395, 0.4815],
         [0.2575, 0.2030, 0.2215, 0.0365],
         [0.9525, 0.3380, 0.8885, 0.1850]],

        [[0.2920, 0.4475, 0.9845, 0.5260],
         [0.2360, 0.9050, 0.1355, 0.3275],
         [0.6610, 0.4270, 0.2745, 0.7100],
         ...,
         [0.2195, 0.6245, 0.0400, 0.5065],
         [0.3820, 0.1765, 0.9430, 0.4065],
         [0.2135, 0.9925, 0.3690, 0.6835]],

        [[0.4270, 0.9370, 0.4250, 0.6505],
         [0.9050, 0.8330, 0.0280, 0.4190],
         [0.0950, 0.1505, 0.4220, 0.5400],
         ...,
         [0.8175, 0.3170, 0.9445, 0.6925],
         [0.9110, 0.3805, 0.1365, 0.1530],
         [0.1525, 0.8580, 0.3225, 0.1525]],

        ...,

        [[0.5560, 0.4620, 0.2075, 0.7330],
         [0.6570, 0.0615, 0.6500, 0.6205],
         [0.3845, 0.7590, 0.4045, 0.9405],
         ...,
         [0.7655, 0.7

In [23]:
#this is what we call one epoch training
for i in range(100):
  print("EPOCH ", i)
  for i, (inputs, target) in enumerate(zip(sample_X, sample_y)):
    output = sample_model(inputs)
    loss = loss_fn(output,target)
    if i % 10 == 0:
      print("   step ",i)
      print(loss.item())
    # Backpropagation
    optim.zero_grad()
    loss.backward()
    optim.step()

EPOCH  0
   step  0
0.012690055184066296
   step  10
0.013567021116614342
   step  20
0.010336017236113548
   step  30
0.016646243631839752
   step  40
0.006546760443598032
   step  50
0.03334365040063858
   step  60
0.0050565809942781925
   step  70
0.01428917981684208
   step  80
0.015130406245589256
   step  90
0.013975250534713268
EPOCH  1
   step  0
0.01226524543017149
   step  10
0.013114964589476585
   step  20
0.009990168735384941
   step  30
0.01608930341899395
   step  40
0.006327258888632059
   step  50
0.032228004187345505
   step  60
0.004888272378593683
   step  70
0.013811713084578514
   step  80
0.014626115560531616
   step  90
0.013507900759577751
EPOCH  2
   step  0
0.011854633688926697
   step  10
0.012677943333983421
   step  20
0.009655876085162163
   step  30
0.015550946816802025
   step  40
0.0061150542460381985
   step  50
0.03114980086684227
   step  60
0.0047254799865186214
   step  70
0.013350294902920723
   step  80
0.014138476923108101
   step  90
0.0130563

In [24]:
#lets see the total loss
loss_total = []
for inputs, target in zip(sample_X, sample_y):
  output = sample_model(inputs)
  loss = loss_fn(output,target)
  loss_total.append(loss.item())

loss_average = np.mean(loss_total)

In [25]:
print(loss_average)

0.0004547981209179852


In [26]:
#lets we see the parameters, that's the weight that we trained
for param in sample_model.parameters():
  print(param.data)

tensor([[1.0507, 2.0075, 2.9946, 3.9481]])


## 5. create inference function

In [27]:
def inference(x1,x2,x3,x4):
  inputs = torch.tensor([[x1,x2,x3,x4]], dtype=torch.float32)
  inputs = inputs/2000
  output = sample_model(inputs)
  output*=2000

  return output[0].detach().numpy()

In [28]:
x1,x2,x3,x4 = 3,4,5,6
inference(x1,x2,x3,x4), function(x1,x2,x3,x4)

(array([49.843983], dtype=float32), 50)